var yuni = {

	attacks : {
	lips: {
		tits: "Yuni bends forwards, and goes for the chest! Her lips wrap around your sensitive nipple, and she begins to suckle like a nursing infant. Lapping at your nub, circles it with her tongue while her lips pull, again and again and again.",
		lips: "Yuni bends you backwards for a dip-kiss like a gentleman on a ballroom floor... she pushes her tongue into your mouth as she locks lips with you, exploring your mouth with her licker while she suckles on your own tongue.",
		penis: "Yuni drops to her knees without warning, shoving her face into your groin for a suckle~ Her lips wrap around your prick, and she begins to suck. Bobbing her head, she sucks your dick as long as she can get away with, a thin strand of drool connecting her lips to your prick as she finally pulls away.",
		vagina: "Yuni drops to her knees and spreads your legs with her paws, pushing her face against your cunt. Rolling her tongue from end-to-end of your slit, she flicks your clit with a slurp of her tongue at the top of each stroke, drooling all over your puss as she eats that muff~",
		ass: "Yuni spins you around with a spank, and drops to her knees behind you. Lips touch pucker moments later, the wolf licking your ass like she's at a dog park with you. Lips suckling on your pucker, her tongue shoves inside and explores before pulling out with a loud, vulgar *SLURP*."
	},
	fingers: {
		tits: "Yuni grabs your breasts for a thorough groping, making sure to rub your nipples with her thumbs.",
		lips: "Yuni fondles your mouth, pushing her digits past your lips and rolling them around... they taste like the other parts of your body she's been groping!",
		penis: "Yuni darts in and shoves her paw between your legs to wrap her fingers around your cock. One vigorous, exhausting, dick-milking handjob later she hops back into a defensive pose.",
		vagina: "Yuni  darts in and shoves her paw between your legs to get her paws on your pussy. She rubs your clitty with her thumb in circles while three fingers explore your vagina. She pulls away, fingers wet, and licks her digits clean.",
		ass: "Yuni goes for your ass, rolling her fingers around inside your pucker, pumping and thrusting them in your ass to get you worked up."
	},
	tits: {
		tits: "Yuni wraps her arms around you and squashes her chest against you from the front. Her breasts pillow and goosh out against your own. '... Mine are bigger, Slut.' she taunts, before hopping back.",
		lips: "Yuni shoves her nipple into your mouth, trying to hold you in place by the back of your head with one paw. The other squeezes her oversized milk-maker, and she floods your mouth with milk.",
		penis: "Yuni pushes you onto your back, dropping her massive mammaries onto your groin. She enwraps her jugs around her breasts and starts a tit-quake, jerking you off forcefully with her breasts, blowing you a kiss as she does.",
		vagina: "Yuni giggles, pouncing you onto her back. She makes your groin disappear with her jugs, and her nipples are juuust big enough to give a good stretching to a gal's cunt... it's a bit milky in there afterwards, though.",
		ass: "Yuni pounces you, but you end up with front-end against the floor. She shrugs, and squishes her tits up against your booty, managing to slip a nipple up into your rear end... grinding it around a little with a feminine giggle."
	},
	sex: {
		tits: "Yuni giggles behind an open palm and pounces you... wrapping her legs around your chest. Somehow, she manages to squish one of your breasts up between her legs, grinding her pussy back and forth over your breast like she's trying to scissor with it... it's wet, tingly, and she hops off with a peck of a kiss to your forehead.",
		lips: "Yuni makes a derisive snort and smirks... 'Eat.' she demands, grabbing the back of your head. Shoving you between her thighs, she forces her cunt against your mouth and starts grinding on your face. Clit shoved into your mouth, she humps your mouth like she had a significantly less female piece between her legs... smearing pussyjuice everywhere.",
		penis: "Yuni pulls a cowboy hat from between her cleavage and puts it on, hip-bumping you to knock you down. Up on top of you, she mounts her girly parts onto the 'pommel' of that saddle between your legs, and with a wet squelch her cunt engulfs you. A short, bouncy ride ensues, Yuni shaking her hat around with a 'Yee-hah!' as she works your member with her cunt, the squelching of her juices loud and vulgar.",
		vagina: "Yuni teases you. 'Did you bring scissors? Hopefully not the safety kind.' Without any more of an explanation, she drops you to the mat with a leg sweep, grabbing both your ankles and pointing your crotch skywards. She sits on your upturned crotch like a throne, smushing her pussy against yours... and rocking her hips like a saw. Rolling her cunt against yours, fluids are swapped, lips and clits catch against each other, and your crotch is soaked in her juices before she lets you up~",
		ass: "Yuni looks at her crotch, then your rear, then yanks a double-ended dildo out of her cleavage. With a chest-bump to the face to knock you over, she sticks one end of the toy in her cunt, and the other end in your tush... rocking and rolling to fuck both orifices with those strong hips of hers~"
	},
	ass: {
		tits: "Yuni turns around and hip-drops you, using the significant girth of her baby-making hips to knock you to the mat. She booty-stomps onto your chest, making the mat reverberate... and squishing whatever cleavage you have with her posterior's cleavage! Grinding and rocking her hips, she giggles madly, all the flesh wobbly and warm... before hopping back into a fighting pose.",
		lips: "Yuni smirks. 'Hungry? No? Too bad.' she teases. She turns around and hip-drops, slamming you to the mat with her rear end... with her naked behind on your face, she makes the world vanish into darkness. 'Eat.' she taunts. She starts grinding her pucker on your mouth, anus rubbing, smearing her scent, trying to force you to tongue her tush if she can get away with it... getting up only when you are desperate for breath.",
		penis: "Yuni stares at your groin like a greedy harlot. '... Mine.' She does a double-footed leg-sweep, holding herself up with her paws to do so... Once your cock is properly pointed skywards, she drops onto it like she's trying to squish a Goomba. Your cock vanishes first into her anal cleavage, second into her pucker... warmth, pressure, and friction engulfing your member. She grabs your legs for leverage, and gives a bouncy, noisy, ball-slapping ride in her rear end before hopping off your bedraggled form.",
		vagina: "Yuni quirks an eyebrow, then looks at your cunt... then at her crotch. She whips a purple double-ended dildo out of her cleavage, shoving one end up her ass. With a leg-sweep, she gets you on your own tush, and sits on your crotch... shoving the other end of that toy into your cunt. A bouncy-ride later, she uses that dildo like a pogo stick in your snatch, until the whole thing is nice and wet. 'Whee!' she teases, hopping back into a fighting pose.",
		ass: "Yuni looks at your rear for a moment... then drags a double-ended dildo out of her cleavage somehow, shoving one end up her booty... She hops forwards, bouncing her breasts off of your face to knock you to the mat, then grabs your legs as handles. Pointing your legs skywards, she faces away from you and sits down... letting the other end of that toy slip into YOUR ass. A bounce-fest begins, the harlot using her own ass to fuck yours with the toy... as she gets plenty of stuffing along the way. 'More!'"
	},
	feet: {
		tits: "Yuni does a flip, knocking you to the padded mat. Her toes go for your breasts... Soft soled digits, toes pinching your nipples and giving a little tug, a few to each... rolling as much of the flesh of your breast as she can grasp with her hind paws.",
		lips: "Yuni embraces you and drops to the mat alongside you... her legs held up. A foot pushes its way to your mouth, her hind paw stuffing a couple of toes past your lips. Pushing and pumping, she strokes your tongue with her toe, before grinding her soft sole over your lips and nose.",
		penis: "Yuni embraces you and drops you to the mat with her, only to scooch back a little and plaster both of her feet on your groin. Tenting her feet around your cock like she's giving it a hat, she grinds the crook of her toes around your cocktip... stroking and rolling, moving to then jerk off your prick with both of her soles.",
		vagina: "Yuni does a leg-sweep to get you on your ass, then plasters her heel on your cunt. Grinding and rubbing, she tries to grind your clitty with her soft heel, moving to roll her entire sole over your cunt back and forth... in a sawing motion culminating in pushing her big toe into your pussy for a brief moment.",
		ass: "Yuni does a leg-sweep to get you on your face, then plasters her foot on your rear end. Shoving the tip of her hindpaw into your rear crack, she finds your pucker and squishes her big toe into it... flexing and pumping it a bit to stretch out your rear with her big, soft toe~"
	}
	},

	defenses : {
	fingers: {
		tits: "Yuni squeaks cutely as her jugs are grabbed. Warm and soft, her massive mammaries squish in your fingers, milk leaking out the front spigots that are her nipples. She goes crosseyed, toes and fingers clenching and unclenching while her breasts are kneaded, nipples pinched and twisted. 'Fuuuuck...' she groans.",
		lips: "A hand in front of her face, Yuni blushes. She opens her mouth with an 'Awm' and takes in your fingers like she's ready for a blowjob. Nursing on your digits -- wherever they've been before this -- she licks and cleans, that soft blush spreading as the sound of her sucking on your fingers is audible. She takes them to the palm before letting them go, clean. 'I'm a good wolf.'",
		sex: "A grab from behind is all it takes to get your hand where it needs to go, her cunt wet and warm to the touch. Her clit's already hard, and she crosses her eyes upwards... clit throbbing underneath exploratory digits, passage squelching and leaving traces of girl-juice behind on probing fingers. 'Ah... ahh-uhhh... whuuuff...' she groans, ears pinning back.",
		ass: "Yuni gulps lewdly... when you reach for her ass, she flops forwards, falling over your lap with her naked ass presented upwards. '... Spank me, Please.' she begs. Whether what follows is a cheek-wobbling, butt-reddening spanken or a pucker-stretching, rectal-probing fingering, she remains on your lap to accept it, shivering and groaning throughout."
	},
	tits: {
		tits: "Yuni grunts. She accepts this challenge, letting her mammaries squish out against your own as you come forwards. Her nipples hard, she does her best in this four-balloon sumo match to try and push you over, but her breasts are just so sensitive at that size! She ends up squeaking and twitching her tail, eyes shut, as her nipples catch against your own time and time again... 'Mmmf...'",
		lips: "Yuni blinks... she winces, but her tail won't stop wagging. Opening her mouth with an 'Ahhh' she accepts a nipple into her mouth. Nursing like an infant, she suckles and licks at your teat... drinking anything that comes out, and nibbling and flicking the nub with her tongue regardless. She suckles until the teat is taken from her, blushing and wagging her tail. '... I'm a good pup.'",
		sex: "Yuni squeaks as she hits the mat, her legs hanging apart in a spread eagle pose. She soon finds her nethers smothering in a pair of mammaries, or at least a cute perky pair of nipples! She tries to close her legs around your torso but has marginal success at best, rolling and bucking her hips to try and use your breasts as a sybian. 'F... fuck me for real!' she teases frustratedly.",
		ass: "Yuni blinks... she's easily tripped, buttocks up in the air. A sumo battle ensues, but not with breast-to-breast, your tits against her buttocks instead. She squeaks and squirms, globes of flesh squishing in both directions, eventually giving your nipple a 'kiss' with a flex of her pucker as you come away from her rear end."
	},
	lips: {
		tits: "Yuni gasps. Naked as her breasts are, she can't keep your face away. A mouth, a nipple, and a gush of milk are what follows... her breasts full to the brim. Whether you went in for a nibble or a nurse, a full mouth is what you get... white lactation filling your cheeks for as many times as you swallow, the cow of a wolf groaning and reeling throughout. '... M-momma wolf, sorry. F-full at this time of day!' she protests cutely.",
		lips: "Yuni bends backwards to your oral assault. She finds herself supported by her upper back like the lady on a ballroom floor, and closes her eyes, lips puckered. A make-out follows, her opening her mouth submissively for your tongue to enter, sucking on it if proffered... or exploring your own oral cavity with her slippery wolf tongue instead, if a hole is what's presented to her. 'Mwah...' she murmurs bashfully as she stands up again.",
		sex: "'Y-you want what? Uhm... mmf.' She leans backwards against the ropes of the ring, spreading her legs. Her nethers are revealed, black, flush, wet... She closes her legs once you get close, the entire world vanishing in the darkness of her thick thighs. The warmth and wetness of her pussy are inescapable at this range, but a squeaking, wobbling, blushing mess is up above once she's done letting you eat her snatch. Her clitty's all hard now!",
		ass: "'You want what? ... Yes, please.' She turns around and drops to all fours, reaching behind to spread her buttcheeks with both paws, letting her pucker 'wink' at you with a flex of her anus. She keeps those cheeks spread until you're up close, letting them make your head disappear. Throughout the booty make-out, she's flexing, squeezing your tongue, 'kissing' right back, and groaning like a whore up front... your face musky with her rear's scent by the time you pull away."
	},
	vagina: {
		tits: "Yuni blinks confusedly as you sit on her chest. She tries to wrap her bosom around your entire groin, but there is no member there. She still squirms cutely as your pussy leaves a trail of your juices between her jugs like a proper pearl necklace, just without the pearls. 'Oof.' she squeaks cutely.",
		lips: "Yuni kneels and awkwardly runs a paw through her hair. 'L-less experience with this one...' she groans bashfully. She opens her mouth and noms the proffered pussy, rolling her lips over it cutely... She finds your clitty and nibbles obediently, sucking on the little nub before starting to lap your pussy like a proper doggy... rolling her tongue from one end of the slit to the other, tasting whatever ELSE has been in there along the way. 'Mmf...'",
		sex: "Yuni gulps. She finds herself with her legs apart in a traditional scissoring pose, but she's the one with her side against the floor, not upright. She tries to maintain dominance over the pose, but finds HER pussy as the one getting fucked, twitching and leaking her juices as you grind on her over and over, face a bit dizzy, panting for breath. 'F... fuck.' she grunts cutely.",
		ass: "'What? I... mmf. Okay.' she teases bashfully. She turns around and drops to all fours -- using her oversized breasts as a form of suspension so she can use her paws to spread her butt-cheeks. She manages to hold herself wide enough for you to get your crotch in there, squeaking and blushing as your clitty bumps her pucker... She 'winks' her anus at you, giving a few small kisses to the proffered puss before standing back up. 'W-wow.'"
	},
	penis: {
		tits: "Yuni pants like a dog... She drops to her back and parts her breasts with her hands, leaving her cleavage open. She lets it close like a pair of Nerf wrecking-balls around your cock, warm, sloshy flesh making your dick disappear. She licks at the exit of her cleavage in case you poke out, but otherwise pants like a skank throughout the titty-fuck, her breasts slamming against your groin with returned inertia with almost enough force to dismount you! '... M... more!'",
		lips: "Yuni runs a paw through her hair and drops to her knees. 'May I suck your cock... please?' she asks awkwardly. Opening her mouth and sticking out her tongue, her eyes half-shut as she gets her treat. She rests her hands on your thighs and bobs her head in your lap, drooling, sucking, clearly flustered and a bit mind-numbed... leaving a coating of her spittle from base to tip of your cock, and a lipstick mark split between your upper groin and balls... a deepthroat whore-print, as she bottoms out. Flustered, rubbing her pussy, she finishes. '... Thank you.'",
		sex: "Yuni can't resist a cock. She drops to her back, spreading her legs then rolling them back in an exaggerated missionary position. 'Fuck meeee!' she groans. Her nethers are warm, wet, and squish around your cock like a velvet vicegrip when you insert, her blushing, breasts bouncing, eyes crossed with mindless lust as she accepts every thrust you have. She gasps and groans, tongue drooling, pussy soaking your groin with arousal as you fuck her silly. 'M... more... don't stop!'",
		ass: "'You want to.... yes, please, PLEASE!' she begs. She drops down into a submissive doggy-style, turning around and using her breasts as suspension so her paws can hold her ass-cheeks apart. 'Fuck my ass!!' Once her pucker is full and warm, she practically melts... face going vapid, tongue lolling out. 'Yeeesss... I love anal...' Her well-practiced hole accepts you to the hilt, a cute 'MMF!' coming from her mouth on every thrust, breath matching your timing perfectly. '... More, more, more!! Please?! I'm gonna cum...'"
	},
	ass: {
		tits: "Yuni lays down with a bashful squeak... and lets you sit on her chest. 'L-lay off the cookies.' she teases cutely. Her sensitive breasts are squished by your booty, two rear globes vying for dominance with a pair of giant mammaries. She finds each of her nipples kissing your pucker at one point or another, and if you're not careful you end up with milk in your ass... 'S-sorry. I'm a momma wuff, they're almost always full.'",
		lips: "'May I? May I!?!' she groans. She drops to a kneeling pose and puts her hands on her knees like a slave, panting. With a butt soon in her face, she dives her nose between your rumpcheeks and smells your pucker with a deep snort, like a social dog at a dog park. The licking begins, the wolf going from stroking the whole length of your ass-crack with her tongue, to kissing your ass full and proper... nursing and smooching your asshole, shoving her tongue inside and exploring whatever she finds, licking around in there like she's trying to wash it. One heady suck on your anus later and she comes away, face musky. '... thank you SO much...' she moans.",
		sex: "'Wait... what?' she squeaks, crosseyed. She sits down, spreading her legs... and instead finds herself with her crotch in the air, groin against your rumpcheeks. She rolls and bounces, trying to get some kind of friction going for herself... her clit occasionally bumping your pucker along the way. 'Ffff.... w-warm.' she groans. There's a cute film of girl-juices in your ass-crack by the time she stands up.",
		ass: "'It's toy time.' she teases cutely. She pulls a double-ended dildo out of her cleavage, offering it with a bashful grin. She turns around and drops to her knees-and-breasts, her oversized jugs serving as suspension to keep her up. She stuffs the fat end of the toy in her ass, turning on a vibration setting... and lets you use the other end as you will. Whether it's shoving it into her, or riding the other end with your ass to fuck HERS, she submits to it, drooling like an idiot. 'M... Mmmmf... a-anal... Butt bitch wolf...' she groans cutely."
	},
	feet: {
		tits: "Yuni lays down with a frustrated, stimulated grunt. She pushes her tits together with her paws to make them squish out... Easy balloons to walk on. Her nipples throb between your toes, leaking a little bit of milky lubrication. They squish, but are strong enough to even support your body if you stand on her chest. 'Mmmf... guh.' she teases cutely.",
		lips: "Yuni drops to all fours in front of you, panting. 'May I worship your feet?' she groans. A proffered sole, proffered toes, she opens her mouth like the canine she is and starts tongue-bathing your feet. Clean or musky, smooth or strange, she licks and sucks on your sole, drooling vulgarly... If you have toes, she moves to those, licking between each digit and sucking on it briefly. She shoves her nose hard into your sole and snorts like she's doing a line of cocaine... sniffing everywhere she can get to. By the time she stands up she looks dizzy! 'F... feeeet.'",
		sex: "Yuni struggles a bit, but ends up on her tush with her legs spread, breasts weighing her down. 'Not fair!' she squawks cutely. Her pussy squelches under your heel, her juices already worked up from all the fighting. Her clit's a tickly point against your sole as you squish and rub with your feet, a cute, defeated look on her face throughout. 'Mmmmf!'",
		ass: "'Wait, what?' she squeaks. She turns around and offers her anus, curiously... down on all fours, spreading her cheeks vulgarly. It's easy to get your foot in there, grinding and rubbing around her anus... she tries to open her pucker in a 'winking' motion with her muscles, and sees if she can get your big toe inside of her... gripping it tightly and blushing. '... Can I suck on your toes now? Please?'"
	},
	}
}

module.exports = yuni;