var fing = ["fingers","hands","paws","finger","hand","paw","thumb","punch","jab","jabs","hook","magic","fist","fists","palm","palms","swat","sextoy","vibrator","crop","tentacle","tentacles","jets","water jets","water jet","arm","arms","elbow","elbows","forearm","forearms","food","slap","smack","backhand","elbow drop","pets","shocks","shock","electricity","electroshocks","electroshock","lightning","collar","hacking","hack","skin","rubs","rub","pat","pats","silberzwiebel","pillow","impact","impacts","hot dog","hot dogs","wrist","wrists","nail","nails","claw","claws","hug","hugs","rolled newspaper","straight","uppercut","haymaker","whip","crosspunch","spank","grope","pull","barrel","barrels","froot loop","KFC","hammer","beer","pinch","towel snap","one thousand muffins","cockcage","slap","weapon","chop","sword","blade","gun","shoot","bullets","ropes","force","punches","cuddles","scratch","squeeze","axe handle","handle","chair","desk","wall","lube","airblast","dab","friendship","bully","gloves","molest","wedgie","facehugger","chest buster","fondle","snowball","ice","clones","rope","mustard","fish","tintenfisch","humiliate","asshugger","grip","grab","evidence","acorn","soap", "chancla"];

var lips = ["lips","mouth","throat","tongue","maw","muzzle","face","head","spell","whisper","whispers","teeth","neck","ear","ears","moans","cheek","cheeks","suction cup","suction cups","fangs","bubbles","meows","nose","hair","bite","bites","headbutt","nibble","nibbles","noms","chin","lick","suck","jaw","purrs","beak","breath","breaths","spit","saliva","snout","taunts","taunt","shin","mountain goat","mountaingoat","science","kiss","voice","forehead","laughs","licks","repents","hoodie","chew","song","sing","venom","purr","rears","motorboat","objection","contradiction","testimony","eat"];

var tits = ["tits","titties","breasts","boobs","boob","nipples","chest","tit","breast","boob","nipple","torso","pecs","nipple piercings","assets","boobies","bust","funbags","melons","udders","hooters","knockers","chesticles","belly","bellybutton","shoulder","shoulders","collarbone","armpits","armpit","back","tummy","milk","stomach","flat chest","big fake balloon tits","gut","back","cleavage","abs","waist","ribs","cider","core values","personality","personalities","navel","tit uppercut","tit hook","tit jab","tit strike","tiddies","breast pocket","wings"];

var sex  = ["sex","pussy","cock","slit","shaft","cunny","cunt","clit","dick","vagina","penis","balls","crotch","clit piercing","cock piercing","manhood","widdler","weenie","package","bulge","folds","strap-on","sheath","cookie","kitty","peach","muffin","cush","vulva","honeypot","cupcake","mons","mound","camel toe","clitty","clit-hood","love button","womb","cervix","egg insertion","impregnation rod","groin","member","foreskin","horn","horns","nut","nuts","testicles","testies","cream","boypussy","knot","fat cock","snu snu","dong","lap","bush","box","piss","panties","clitoris","burger","fish taco","fur burger","axe wound","labia","g-spot","cum","cockslap","girlcum","thighs","crown","tip","swanstucker","cooch","hip","banana","waist band","laserdildo","business","cockhead","precum","piss","hump","humping","orgasm","I have","no idea","taco"];

var ass  = ["ass","butt","rump","rear","butthole","buttcheeks","tail","tails","tail spade","tailhole","thigh","asshole","bottom","anus","arse","back door","bootyhole","man pussy","rosebud","star","booty","hips","pucker","anal beads","buns","bun","McBuns","tush","donut","prostate","ass stink","asscheeks","bubblebutt","lower back","tushy","back pockets","panties behind","asscrack","defense"];

var feet = ["feet","legs","toes","toe","knee","foot","leg","footpaws","feetpaws","kick","kicks","heel","heels","knees","calf","calfs","hoof","hoves","stomp","stomps","ankle","ankles","sole","soles","sock","socks","step","steps","jump","jumps","ribbons"];

var body = ["body","figure","sexy dance","sexiness","pose","strip tease","musk","wiggles","wiggle","za warudo","[eicon]za warudo[/eicon]","[eicon]oraora[/eicon]","[eicon]mudamuda[/eicon]","sight","eyes","kidney","fire","fireblood","blood","roll","love","fabric","mat","ground","floor","sweat"];

var sight = ["sight","eyes","body","back","mind","mat","ground","floor"];

var bodyparts = {
	destinies: { fingers: fing, lips: lips, tits: tits, sex: sex, ass: ass, feet: feet, sight: sight },
	origins: { fingers: fing, lips: lips, tits: tits, sex: sex, ass: ass, feet: feet, body: body }
}

module.exports = bodyparts;