var robert = {
	attacks : {
		lips: {
			tits: "Robert steps forward, into your personal space, and wraps his arms around your waist. ‘Going up?’ He taunts as he arches back and lifts you off the ground. As your feet dangle helplessly off the mat, he looks up at your and winks, before pressing his face into your chest. Suddenly you feel a warm sensation clamp onto your nipples as he begins sucking and licking, his warm mouth teasing your nipples with expert precision.",
			lips: "Robert comes at you with desire in his eyes. He thrusts a hand out at your head. You flinch away, expecting a strike, only to find he grabbed the back of your head. ‘That’s two for flinching,’ he mocks you with an insidious grin, before he pulls your head forcefully forward, and plants a kiss on your lips. It’s rushed and brutal at first, but as he slips a tongue between your lips, he softens, and slows. Savoring the kiss, his lips warm against your own as he sucks on your bottom lip, lightly biting. He pulls away with a wink and a smile, leaving you gasping.",
			penis: "Robert swaggers over to you, a spring in his step and a mischievous grin. He licks his lips and makes a dive for your waist. He wraps his arms around you and takes you down to the mat, where he folds your legs up and over your head, with your back firmly pinned to the mat. He looks down at you from between your thighs and flashes you his pearly whites. Then he grabs the waist-band of your gear and pulls it down, letting your cock flop out. He looks back to you and whistles, ‘Not too shabby.’ He compliments you before he opens his mouth and sucks your length in in one fell swoop. Sucking and bobbing his head, Robert causes you to stifle a moan as his warm mouth works on your shaft. Satisfied, he pulls away, your cock falling out of his mouth with a *plop.* He stands up and wipes away a strand of drool from his chin, motioning for you to get back to your feet. ",
			vagina: "Robert strides toward you and drops to his knees at the last second and yanks your legs out from under you. He grabs onto your arms and pins them down. Spreading your legs, wedging himself in-between, he drops his face to your waist and pulls down your undergarments with his teeth. Then, he glances up at you with his eyes and winks, before he dives into your box face-first, licking every inch of your clit. You can feel the light stubble of his chin tickling your sensitive areas. Satisfied, he stands up and wipes his face clean.",
			ass: "Robert manages to sweep you off your feet. You turn and fall on your hands and knees, only to have Robert land on your back, flattening you out. You struggle under him and he sits up, grabbing your legs and prying them open. He yanks them up over his shoulders and suddenly you feel your toes curl as he begins licking your hole. His tongue winds its way all around your ass, teasing your sensitive pucker. It climaxes as he slips that warm tongue deep into your hole causing you to moan out loud. The he drops you and pulls away."
		},
		fingers: {
			tits: "Robert thrusts his hands forward, taking hold of your chest, kneading and rubbing your nipples with his thumbs.",
			lips: "Robert crams his fingers into your mouth, swirling them around. ‘Just getting your ready for something bigger sweetheart,’ He boasts.",
			penis: "Robert puffs out his chest, bumping yours and pushing you back until you find yourself pinned in the corner. He shoves his arm forcefully against your throat and pushes, meanwhile, he slips his hand into your trunks and grabs hold of your cock. He thumbs over it a bit until grabbing it fully. He gives it a few good pumps, making you grunt and hump his hand needily, before letting go.",
			vagina: " Robert puffs out his chest, bumping yours and pushing you back until you find yourself pinned in the corner. He shoves his arm forcefully against your throat and pushes, meanwhile, he slips his hand into your undergarments. With a wink, he slowly drags his fingers around your clit, thumbing the sensitive areas. He begins to massage and stimulate your womanhood before shoving a finger inside and swirling it around. Pulling his hand back out, he crams that finger into your mouth, forcing you to taste your own juices before wiping it off on your clothes.",
			ass: "Robert grabs you around the waist and lifts you up over his shoulder. Walking around with your helplessly kicking, he spanks you a few times before drawing down the waistband of your gear. Soon, you start to kick like mad as he plunges a finger into your pucker."
		},
		tits: {
			tits: "Robert grabs you up in a bearhug, squashing you into his chest, flexing his muscles. It’s like being ground against a washboard.",
			lips: "Robert wraps and arm around your head, falling to the canvas with your trapped underneath him in a headlock. Your face is shoved into his muscular chest and he crams his meaty pec into your mouth, forcing you to lick the salty sweat from his chest.",
			penis: "Robert wraps his arms around your thighs, lifting you up high, holding your there over his head before dropping you back onto the mat. He remains perched just over you. You lie there dazed and out gasping for breath when you feel a tingle in your groin. As your vision clears, you see Robert lying above you, flexing his meaty pecs over your cock, clamping them tightly around your manhood. He rubs your cock between the mounds of muscled flesh for a bit before standing and looking down at you, making his pecs flex and dance to taunt you.",
			vagina: "Robert trips you and then drops down on top of you. He slowly snakes his way up your body, starting out from your feet. Never breaking eye-contact until he gets over your cunt. He stops and drops down, rubbing his chest against your groin. It is… certainly an experience.",
			ass: "Robert sweeps behind you and wraps his muscled arms around your waist and lifts you up. Slamming you to the mat, he flexes and jiggles his meaty pecs against your ass."
		},
		sex: {
			tits: "Robert sweeps your legs out from under you, sending you falling flat on your back. Before you hit the mat, he’s there on top of you, flexing and straddling your chest. Pulling his cock from his singlet, he begins to grind down on you, rubbing his own shaft down the center of your chest.",
			lips: "While pinned to the mat, Robert sits down on your chest and scoots up until his bulge is resting on top of your lips. Flexing and smiling down at you he wraps a hand around your head and pulls it up, smothering you in his crotch, forcing you to breathe in his scent and taste the sweat accumulating on his balls. ‘Give it a kiss and I’ll let you up,’ He taunts, slipping his cock out of his singlet and slapping your face with it.",
			penis: "Robert holds you tight to his body before dropping down on top of you, pinning your back to the mat. He works his legs between yours and spreads them. He begins to press his bulge down against your own, rubbing his thick shaft against your own swelling member, frotting you.",
			vagina: "Robert looks at you with a predatory hunger in his eyes. Picking you up and slamming you to the mat, he struggles with your undergarments, pulling them down as he frees his thick shaft from his singlet. Pinning your arms above your head with one of his hands, he uses the other to guide his engorged cock straight towards your cunt. ‘You’re a lucky little bitch to get fucked by me,’ he taunts as he slides all the way in, slowly at first. Then he pulls out and shoves in again. And again. Until he is thrusting back and forth into your pussy. Your toes curl as he uses his free hand to tickle and stimulate your clit. Just when you think he’s going to fuck your brains out, he pulls his cock free of your slit and stands up.",
			ass: "Robert barrels into you, taking you both down to the mat. As you two struggle, twisting around for dominance, limbs entangled with one another’s, he flips you over onto your stomach. Suddenly you feel him yank down your waist band and slap your bare ass. You try to struggle free but he holds you down, a hand on the back of your neck. You hear him spit then suddenly you feel it. A finger probing the inside of your sphincter. You kick and struggle to no avail. The finger turns to two, then three, and finally they are removed only to be replaced by Robert’s swollen cock. Slowly he goes all the way in. Then he pulls out and thrusts in again until he is humping you like a dog in heat, his shaft wrecking the inside of your tight pucker before he pulls out."
		},
		ass: {
			tits: "Robert throws you to the ground. As you lie on your back and look up you see Robert standing over you, facing towards your feet. He holds his hands up behind his head and shakes his hips seductively and drops down, planting his muscled ass down on your chest. He grinds those hips against your chest, his hard glutes crushing you.",
			lips: "Robert takes you down to the mat and breaks out some, frankly, impressive wrestling skills you didn’t know he had. You’re lying on your stomach when he grabs your arms and pulls them up painfully behind your back. You start to roll, reflexively as he walks his legs around your body until you’re lying on your back. Taking one big step with his right leg, he stomps down on the other side of your head. Now, with both legs on either side of your head, he uses that right legs to scoop up your head, and locks his ankle behind his left knee, clamping in a figure-four. You are pinned down to the mat, your face shoved into Robert’s ass and balls. He flexes his thighs around your head and arches his back up, causing your head to be shoved even deeper into the hold. You can barely make out what he’s saying, ‘How do you like my headscissors, bitch?’ He asks, laughing sadistically. Helpless to escape, he eventually lets up and gets off of you.",
			penis: "Robert takes you down to the mat and straddles you, sitting down on your stomach. You squirm under him, but he keeps you pinned as he reaches back and pulls your engorged cock from your gear. Then, slipping his own singlet down over his ass, he sits back. He flexes those muscular glutes around your shaft, and begins to grind on your, causing you to whimper in need. Then he sits up and grabs your cock with his hand before sitting back, his ass greedily swallowing up your length. Finally, sitting back fully, his ass flexes tightly around your cock, the warm insides of his hole massaging your penis. He begins to buck up and down, riding your like a bronco, threatening to milk your cock with his tight ass. Thankfully he stands up, releasing you.",
			vagina: "Robert pulls out a double-sided dildo from god knows where and saunters over to you. He pins you flat on your back and crams the dildo inside of your cunt. Then, he shoves the other end into his anus and sits back, and starts to grind his ass up and down, causing that dildo to pull in and out of your own cunt. After a while of this, Robert stands up and takes that dildo with him.",
			ass: "Robert produces a double-ended dildo and stalks over to you. Shoving your forcefully into a corner he turns you around and works the dildo into your tight pucker. Then, he turns around and does the same to his own anus. After both ends of the dildo are inside each of you respectively, he begins to push his hips back, riding the dildo and causing it to fuck your own hole."
		},
		feet: {
			tits: "Robert rears back and throws a kick at your chest. It isn’t too hard but it sends you sprawling on your back. As you look up you see him standing over you, a foot in mid-air. Suddenly, he stomps down, grinding his heel into your tender chest, his toes teasing your nipples.",
			lips: "Robert grabs you up by the legs and drops you down onto your back. Keeping his grip on your legs he holds them each under his arms. Sitting back on his butt, he puts his legs around your torso. As you lay back, helplessly in his grip he brings his feet up over your face and wiggles his toes. ‘I’d hold my breath if I were you,’ he coos before he shoves those feet into your face. He clamps on to your nose and rubs his soles across your face. The sweaty fabric of his socks smothering you. He then shoves a toe inside of your mouth and all you can taste is sweat and musk. Finally, he lets you go but the scent of man sweat lingers in your nostrils.",
			penis: "Robert sweeps your legs out from beneath you, sending you sprawling onto your back. You try to scramble away but are stopped in your tracks as Robert stomps down, stopping just before he makes contact with your crotch. You look up at him, fear in your eyes as he says, ‘Now now, stay still or I’ll have to stomp em.’ Then he slowly begins to grind his heel into your cock. Your groin responds and hardens, your cock head popping out from your waistband. ‘Oh, you like this huh?’ He taunts as he wraps his toes around your cock head and starts to rub it. You start leaking precum before he pulls his foot away.",
			vagina: "Robert trips you and stomps onto your groin. Looking down at you he smiles as he starts to press his toes against your cunt. He rubs his toes around your clit and slips his big toe inside before he steps away, laughing at you.",
			ass: "Robert trips you and flips you onto your stomach. As you lay there he begins to cram his toes between your cheeks, teasing your pucker."
		}
	},

	defenses : {
		fingers: {
			tits: "Robert moans in his throat as you clamp onto his meaty pecs with your hands and squeeze. ‘Fuuuck…’",
			lips: "Robert’s eyes go wide as you shove your fingers into his mouth. He tries to pull away but is unable as your swirl your finger into his mouth, forcing him to suck on your digits.",
			sex: "Robert nearly collapses into you as you wrap your hand around his junk and start to pull, ‘No… please th-’ he stops mid-sentence as he practically melts.",
			ass: "Robert grits his teeth as you shove a finger into his sphincter, causing him to rise onto his toes as his pucker squeezes around your digits."
		},
		tits: {
			tits: "Robert grunts as you squeeze him, shoving your chest against his.",
			lips: "Robert swings his arms wildly as his mouth is shoved onto your nipple and forced to suck like a nursing babe. When you finally release him, he pulls back and gasps for air.",
			sex: "Robert twists and turns, trying to get free from your grasp, but is unable to as you clamp onto his cock with your chest, your teasing sending shivers up his spine.",
			ass: "Robert is… confused to say the least, as you press your chest to his ass and begin to grind, yet somehow it turns him on."
		},
		lips: {
			tits: "Robert gasps as your lips clamp onto his nipples and your tongue swirls around his sensitive chest, causing his cock to swell.",
			lips: "Robert fights it at first, but eventually melts into the kiss, eagerly trying to taste every inch of your mouth and whining when you pull away.",
			sex: "’No wait!’ is all Robert can say before you yank his singlet down and pull his thick cock out. As you wrap your lips around it and begin to suck, his knees begin to wobble and he nearly falls over. ",
			ass: "Robert is laying on his stomach when you lean in and press your lips between his cheeks. He blushes but melts like butter as your expert tongue swirls around his hole. He reaches back and grabs your head, and thrusts his hips up further into your waiting tongue. He can’t get enough of you rimming him."
		},
		vagina: {
			tits: "Robert looks up at you, wide eyed as you sit down, rubbing your cunt against his chest. His cock tents in his singlet as he watches you rub yourself all over his muscled chest.",
			lips: "Robert looks confused as you straddle his chest but then realization dawns on him as you shove his head into your muff. He kicks his legs wildly as he’s smothered by your box, ‘Mmmmmff!’",
			sex: "Robert lies on the mat in a daze as you drop down and yank his cock free of his gear. ‘Wait, what are you- OH FUCK’ he moans as you draw his cock into your pussy, the inner walls stretching around and massaging his thick cock.",
			ass: "Robert blushes, but is turned on none-the-less as you scissor with him, rubbing your pussy against his anus."
		},
		penis: {
			tits: "Robert flexes his pecs around your cock instinctively as you rut against his chest. ‘Oh, yeah,’ he pants, ‘fuck my chest!’",
			lips: "Robert glances up to see you drop down onto his chest, your cock at the ready. ‘wait, what are you doi- MMMMFFF’ he’s cut off as you push your thick shaft into his mouth. He begins to suck and lick every inch he can, spittle leaking from the sides of his mouth.",
			sex: "Robert’s cock swells to meet yours as you begin to grind against him. ‘Agh… fuck no more, please’ he whines.",
			ass: "Robert gasps as you thrust into his tight hole. He squirms and twists but as your cock begins to batter his prostate he moans like a bitch in heat, and begins to thrust back, wanting you deeper inside of him."
		},
		ass: {
			tits: "Robert coughs as you squash him under your rump. Your ass pressing down on him squeezing the air out of his lungs, he pleads with you to get off him.",
			lips: "Roberts eyes fly open as you sit back on his face. He screams but it is muffled under your rump. He tries to bridge up and escape, but is unable to and is completely at your mercy as you grind on his face, causing a tent to form in his singlet.",
			sex: "Robert looks up at you, mouth slightly open and eyes fixed on yours as you pull his cock free and slowly start to grind on him. ‘Wait, are you going t-OH FUCK YES’ he shouts as you suck his cock into your sphincter, your pucker stretching around his girthy shaft. He humps and bucks wildly feeling every inch of your tight rectum, practically begging to cum.",
			ass: "Robert looks skeptically at you as you produce a double ended dildo. ‘What are you doing with that’ he asks nervously as you shove it into your own anus. ‘Wait, no don’t do that’ he continues as you make your way to him and shove the other end into his anus. He struggles at first but eventually his eyes flutter shut as he moans and thrusts down onto the dildo."
		},
		feet: {
			tits: "’Ah, fuck’ Robert groans as you step on his chest. He struggles to breath from the pressure and then he starts to squirm as you toy with his nipples using your nimble toes.",
			lips: "Robert glares up at you as you dangle your foot in front of him, ‘no,’ he warns, ‘don’t you dare!’ but you cut him off, planting your foot onto his face, shoving your toes into his mouth and smothering him beneath your sole.",
			sex: "Robert lays on the mat, looking up at you standing ominously over him. ‘What are you gonna do?’ he asks, watching you warily. You answer by planting your foot onto his cock and beginning to tease, which causes Robert to moan and hump your foot needily.",
			ass: "Robert doesn’t have any time to respond as you flip him over and knock him flat. You step on his ass, triumphantly posing over him before cramming a toe between his cheeks and tickling his hole, which makes Robert spasm under you."
		},
	}
}

module.exports = robert;